source 'https://github.com/CocoaPods/Specs.git'  #官方仓库地址
#source ‘git@localhost:/git/autelSpec.git’  #私有仓库地址

use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

def shared_pod
    pod 'SVProgressHUD', '~> 2.2.2'
end

# 平台工程

target 'MaxiAP200FileBrowser' do
    
    project 'MaxiAP200FileBrowser.xcodeproj'
    shared_pod
end

