//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxiDas808.rc
//
#define IDBack                          8
#define IDReturn                        13
#define ID0                             0x30
#define ID1                             0x31
#define ID2                             0x32
#define ID3                             0x33
#define ID4                             0x34
#define ID5                             0x35
#define ID6                             0x36
#define ID7                             0x37
#define ID8                             0x38
#define ID9                             0x39
#define IDD_ABOUTBOX                    100
#define IDD_MAXIDAS808_FORM             101
#define IDC_TAB_Switch                  101
#define IDC_BTN_Add1                    101
#define IDD_Uiinput_Tip                 102
#define IDC_BTN_Add2                    102
#define IDD_DATALOGDLG                  103
#define IDC_BTN_Add3                    103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_BTN_Add4                    104
#define IDC_BTN_Add5                    105
#define IDD_PROPPAGE_Text               106
#define IDC_BTN_Add6                    106
#define IDR_MAINFRAME                   128
#define IDR_MaxiDas808TYPE              129
#define IDR_A_DataStreamText            129
#define IDD_DIALOG_TopBar               130
#define IDR_A_DataStreamGraph           130
#define IDD_DIALOG_BottomBar            131
#define IDD_DIALOG_Menu_BottomBar       131
#define IDR_A_MultiSelected             131
#define IDD_DIALOG_TitleBar             132
#define IDR_A_MessageBox_Ok             132
#define IDR_A_MessageBox_Yes            133
#define IDR_A_MessageBox_Back           134
#define IDI_BTN_IN                      134
#define IDR_A_ScanSelect                135
#define IDI_BTN_OUT                     135
#define IDR_MAINFRAME1                  136
#define IDR_A_Menu                      136
#define IDR_A_ActTest                   137
#define IDI_HOME_IN                     137
#define IDI_ICON1                       138
#define IDI_BTN_DISABLE                 138
#define IDB_BTN_OUT                     139
#define IDB_BTN_DISABLE                 140
#define IDB_BTN_IN                      141
#define IDB_BITMAP1                     142
#define IDB_HOME_IN                     142
#define IDB_BITMAP2                     143
#define IDB_BTN_CHECKED                 143
#define IDB_BITMAP3                     144
#define IDB_BTN_SCREEN_SHOT             144
#define IDB_SCAN_BTN_IN                 146
#define IDB_SCAN_BTN_OUT                147
#define IDB_SCAN_BTN_DISABLE            148
#define IDB_BITMAP4                     149
#define IDB_Meter                       149
#define IDB_IMAGES_Alert                150
#define IDB_BTN_Help                    151
#define IDB_BTN_SCREEN_SHOT_F           152
#define IDB_BTN_Help_F                  153
#define IDB_HOME_IN_F                   154
#define IDD_DIALOG1                     155
#define IDB_BITMAP5                     156
#define IDB_BTN_LOGGING                 156
#define IDB_BITMAP_BUSY1                157
#define IDB_BITMAP_BUSY0                158
#define IDR_MENU1                       162
#define IDM_DATALOG                     162
#define IDD_DIALOG_LOGGING              163
#define IDB_BITMAP_RECORDING            164
#define IDB_BTN_RECORDING               164
#define IDB_BTN_FINISHE_REC             165
#define IDD_DIALOG_PowerBalance         168
#define IDD_VIN_INPUT                   170
#define IDD_DIALOG_List_BottomBar       171
#define IDD_PROPPAGE_Graph              313
#define IDR_MENU_Tool                   315
#define IDD_VIEWUIMENU                  316
#define IDD_VIEWUIACTTEST               317
#define IDD_VIEWUIDATASTREAM            318
#define IDD_VIEWUIECUINFO               319
#define IDD_VIEWUIFREEZEFRAME           320
#define IDD_VIEWUIINPUT                 321
#define IDD_VIEWUIMESSAGEBOX            322
#define IDD_VIEWUIPICTURE               323
#define IDD_VIEWUISCANSELECT            324
#define IDD_VIEWUITROUBLECODE           325
#define IDD_VIEWUIMULTISELECTED         326
#define IDD_VIEWUIACTTEST2              327
#define IDD_VIEW_UITIMEPROGRESS         327
#define IDD_VIEWUIPOWERBALANCE          328
#define IDD_VIEWUILIST                  329
#define IDD_PROPPAGE_GraphCombo         330
#define IDD_DIALOG_DataStream_BottomBar 331
#define IDD_DIALOG_Trouble_BottomBar    332
#define IDD_DIALOG_FreezeFrame_BottomBar 333
#define IDD_DIALOG_MultiSelected_BottomBar 334
#define IDD_DIALOG_MessageBox_BottomBar 335
#define IDD_DIALOG_ScanSelect_BottomBar 336
#define IDD_DIALOG_Input_BottomBar      337
#define IDD_PROPPAGE_Anolog             338
#define IDD_DIALOG_DataStream_BottomBar_PlayBack 341
#define IDD_DIALOG_Menu_BottomBarPlay   342
#define IDD_DIALOG_EcuInfo_BottomBar    343
#define IDD_DIALOG_ActTest_BottomBar    344
#define IDD_DIALOG_ActTest_BottomBar2   344
#define IDD_DIALOG_Picture_BottomBar    345
#define IDD_snapshot                    346
#define IDD_DigitalKeyBoard             347
#define IDD_DIALOG_TimeProgress         348
#define ID_Btn_Home                     1000
#define ID_Btn_Back                     1001
#define ID_Btn_Error_Report             1001
#define ID_Btn_Error_Report11           1001
#define ID_Btn_One                      1002
#define ID_Btn_Latest                   1002
#define ID_Btn_Start                    1002
#define ID_Btn_Status                   1003
#define ID_Btn_History                  1003
#define ID_BTN_FREE_0                   1003
#define ID_Btn_                         1003
#define IDC_COMBO_Path                  1004
#define IDC_LIST_Menu                   1004
#define ID_Btn_Record                   1004
#define ID_Btn_Back3                    1004
#define ID_BTN_FREE_3                   1004
#define IDC_LIST                        1005
#define ID_Btn_PlayBack                 1005
#define ID_Btn_Home3                    1005
#define ID_Btn_History2                 1005
#define ID_Btn_Two                      1006
#define ID_Btn_History3                 1006
#define ID_Btn_Four                     1007
#define ID_Btn_History4                 1007
#define ID_Btn_Print                    1008
#define ID_Btn_Back2                    1008
#define ID_Btn_Stop                     1009
#define IDC_CHECK1                      1009
#define IDC_CHECK_Demo                  1009
#define IDC_BUTTON_Yes                  1009
#define ID_Btn_Print2                   1009
#define IDC_CHECK                       1009
#define ID_Btn_Save                     1010
#define IDC_BUTTON_No                   1010
#define ID_Btn_Print3                   1010
#define ID_Btn_Zoom                     1011
#define ID_Btn_OK                       1011
#define IDC_BUTTON_Ok                   1011
#define ID_Btn_Prev                     1011
#define ID_Btn_MoveUp                   1012
#define ID_Btn_SelectAll                1012
#define IDC_BUTTON_Cancel               1012
#define ID_Btn_DisplayDTC               1012
#define ID_Btn_Next                     1012
#define ID_Btn_Prev2                    1012
#define ID_Btn_ToTop                    1013
#define ID_Btn_ClearAll                 1013
#define IDC_BUTTON_Back                 1013
#define ID_Btn_Zoom3                    1013
#define ID_Btn_QuickErase               1013
#define ID_Btn_MoveUp2                  1013
#define ID_Btn_FreezeFrame              1013
#define ID_Btn_MoveDown                 1014
#define IDC_LIST_Trouble                1014
#define ID_Btn_No                       1014
#define IDC_LIST_EcuInfo                1015
#define ID_Btn_Cancel                   1015
#define ID_Btn_NextChannel              1015
#define ID_Btn_ToTop2                   1015
#define IDC_LIST_FreezeFrame            1016
#define ID_Btn_Yes                      1016
#define ID_Btn_PrevChannel              1016
#define IDC_EDIT_Message                1017
#define IDC_STATIC1                     1017
#define ID_Btn_Page_Up5                 1017
#define IDC_COMBO1                      1018
#define ID_Btn_Save2                    1018
#define ID_Btn_OK_                      1018
#define FreeBtn                         1018
#define ID_BTN_FREE_1                   1018
#define IDC_COMBO2                      1019
#define ID_BTN_FREE_2                   1019
#define IDC_COMBO3                      1020
#define ID_Btn_PlayStop                 1020
#define ID_Btn_En_Metric                1021
#define IDC_COMBO4                      1021
#define IDC_SLIDER1                     1021
#define ID_BTN_FREE_4                   1021
#define IDC_STATIC2                     1022
#define IDC_STATIC_SLIDER1              1022
#define IDC_COMBO5                      1022
#define IDC_STATIC3                     1023
#define ID_Btn_Delete                   1023
#define IDC_SLIDER2                     1023
#define IDC_COMBO6                      1023
#define IDC_STATIC4                     1024
#define IDC_STATIC_SLIDER2              1024
#define ID_Btn_Page_Down                1024
#define IDC_COMBO7                      1024
#define IDC_LIST1                       1025
#define ID_Btn_Page_Down2               1025
#define ID_Btn_OK2_                     1025
#define IDC_COMBO8                      1025
#define ID_BTN_FREE_5                   1025
#define IDC_LIST_MultiSelect            1026
#define IDC_COMBO9                      1026
#define IDC_EDIT_Input                  1027
#define IDC_Anolog1                     1027
#define IDC_PROGRESS_Scan               1028
#define IDC_Anolog2                     1028
#define IDC_LIST_Scan                   1029
#define IDC_LIST_ActTest                1030
#define IDC_EDIT1                       1030
#define ID_Btn_Screen_Shot              1031
#define IDC_BUTTON1                     1031
#define IDC_EDIT_FILE_DETAIL            1031
#define ID_Btn_Screen_Shot_New          1032
#define ID_Btn_Screen_Shot_New2         1033
#define ID_Btn_Help                     1033
#define IDC_BUTTON4                     1033
#define ID_Btn_Help2                    1034
#define ID_Btn_Error_Report2            1034
#define IDC_BUTTON3                     1035
#define IDC_STATIC_FILE_NAME            1036
#define IDC_EDIT_FILE_NAME              1037
#define IDC_STATIC_FILE_DETAIL          1038
#define ID_Btn_Record2                  1039
#define ID_BTN_SHOW_HELP                1040
#define IDC_PROGRESS1                   1041
#define IDC_PROGRESS                    1041
#define IDC_STATIC_DownText             1042
#define IDC_EDIT_VinCode                1045
#define IDC_STATIC_HELP                 1046
#define IDC_STATIC_HELP2                1047
#define IDC_EDIT_JobCode                1048
#define IDC_STATIC_HELP3                1051
#define IDC_EDIT_RegistrationCode       1052
#define ID_BTN_HELP_DATASTREAM          2000
#define ID_Btn_READ                     2001
#define ID_Btn_READ2                    2003
#define ID_Btn_BrdCtrl                  2003
#define ID_UIMENU_BACK                  32776
#define ID_UIMENU_NEWCAR                32782
#define ID_UIMENU_REUSE                 32783
#define ID_UITROUBLECODE_BACK           32787
#define ID_UIECUINFO_BACK               32789
#define ID_UIFREEZEFRAME_BACK           32790
#define ID_UIPICTURE_BACK               32791
#define ID_DATALOGGING                  32792
#define ID_DATALOGING_ON                32793
#define ID_DATALOGGING_OFF              32794
#define ID_DATALOGING_ON32795           32795
#define ID_DATALOGING_OFF               32796
#define ID_DATALOGING_REPORT            32797
#define ID_UIDATASTREAMTEXT_BACK        32799
#define ID_UIDATASTREAMGRAPH_BACK       32800
#define ID_UIDATASTREAMGRAPH_ONE        32801
#define ID_UIDATASTREAMGRAPH_TWO        32802
#define ID_UIDATASTREAMGRAPH_FOUR       32803
#define ID_UIDATASTREAMGRAPHCOMBO_BACK  32804
#define ID_UIDATASTREAMGRAPH_STOP       32807
#define ID_UIMULTISELECTED_CANCEL       32808
#define ID_UIMULTISELECTED_OK           32809
#define ID_UIMULTISELECTED_SELECTALL    32810
#define ID_UIMULTISELECTED_CLEARALL     32811
#define ID_UIINPUT_OK                   32816
#define ID_UIINPUT_CANCEL               32817
#define ID_UIMESSAGEBOX_YES             32818
#define ID_UIMESSAGEBOX_NO              32819
#define ID_UIMESSAGEBOX_OK              32820
#define ID_UIMESSAGEBOX_CANCEL          32821
#define ID_UIMESSAGEBOX_BACK            32822
#define ID_UIMESSAGEBOX_ANYKEYRETURN    32823
#define ID_UISCANSELECT_OK              32824
#define ID_UISCANSELECT_CANCEL          32825
#define ID_UISCANSELECT_STOP            32826
#define ID_UISCANSELECT_SAVE            32827
#define ID_UISCANSELECT_DISPLAY         32828
#define ID_UISCANSELECT_QUICK           32829
#define ID_UISCANSELECT_CONTINUE        32830
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_HELP                        65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
