/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_example_jnitest_UsBDevice */

#ifndef _Included_Autel_BlueTooth
#define _Included_Autel_BlueTooth
#ifdef __cplusplus
extern "C" {
#endif
	int OpenJ2534BlueTooth();
	int CloseJ2534BlueTooth();
	int SendToJ2534BlueTooth(char const* pData, int cbSize);
	int ReceiveFromJ2534BlueTooth(char *pData, int bufferSize);
#ifdef __cplusplus
}
#endif

#endif
